server:
  port: 8083


spring:
  application:
    name: leyou-search
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 121.41.85.42:9300
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5