server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 121.41.85.42
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5


leyou:
  jwt:
    pubKeyPath: E:\springcloud\leyou\rsa\rsarsa.pub # 公钥地址
    cookieName: LY_TOKEN